
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>  
    <title>Create Task Form</title>
</head>
<body class="bg-gray-200 p-8">
    
    <div class="max-w-md mx-auto bg-white rounded p-6">
        <h2 class="text-xl font-semibold mb-4">Crear Nueva Tarea</h2>
        <form action="create" name="create" id="create" method="post">
            <!-- Descripción de la Tarea -->
            <div class="mb-4">
                <label for="descripcion" class="block text-sm font-medium text-gray-700">Descripción de la Tarea <span class="text-red-500">*</span></label>
                <input type="text" id="description" name="description" class="mt-1 p-2 w-full border-gray-300 rounded-md focus:ring focus:ring-indigo-200 focus:outline-none" required>
            </div>
            
            <!-- Estado de la Tarea -->
            <div class="mb-4">
                <label for="status" class="block text-sm font-medium text-gray-700">Estado de la Tarea</label>
                <select id="status" name="status" class="mt-1 p-2 w-full border-gray-300 rounded-md focus:ring focus:ring-indigo-200 focus:outline-none">
                    <option value="pendiente">Pendiente</option>
                    <option value="finalizada">Finalizada</option>
                </select>
            </div>
            
            <!-- Fecha de Inicialización -->
            <div class="mb-4">
                <label for="date_ini" class="block text-sm font-medium text-gray-700">Fecha de Inicialización <span class="text-red-500">*</span></label>
                <input type="date" id="date_ini" name="date_ini" class="mt-1 p-2 w-full border-gray-300 rounded-md focus:ring focus:ring-indigo-200 focus:outline-none" required>
            </div>
            
            <!-- Fecha de Finalización -->
            <div class="mb-4">
                <label for="date_end" class="block text-sm font-medium text-gray-700">Fecha de Finalización</label>
                <input type="date" id="date_end" name="date_end" class="mt-1 p-2 w-full border-gray-300 rounded-md focus:ring focus:ring-indigo-200 focus:outline-none">
            </div>
            
            <!-- Usuario -->
            <div class="mb-4">
                <label for="user" class="block text-sm font-medium text-gray-700">Usuario <span class="text-red-500">*</span></label>
                <input type="text" id="user" name="user" class="mt-1 p-2 w-full border-gray-300 rounded-md focus:ring focus:ring-indigo-200 focus:outline-none" required>
            </div>
            
            <!-- Botón de Enviar -->
            <div class="mt-4">
                <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-semibold py-2 px-4 rounded focus:outline-none focus:ring focus:ring-blue-200">Crear Tarea</button>
            </div>
        </form>
    </div>
</body>
</html>
