
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmar Eliminación de Tarea</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="bg-gray-100">
    <div class="max-w-xl mx-auto mt-10 p-6 bg-white shadow-md rounded-md">
        <h1 class="text-xl font-bold mb-4">¿Estás seguro de eliminar esta tarea?</h1>
        <p class="text-gray-700 mb-4">Esta acción no se puede deshacer. ¿Estás seguro de que deseas eliminar esta tarea?</p>
        <div class="flex justify-center space-x-4">
        <form  method="post">
                <input type="hidden" name="id" value="<?php echo $id; ?>">
                <button type="submit" name="confirm_delete" class="inline-block px-4 py-2 font-medium text-black bg-red-600 rounded-md hover:bg-red-500 focus:outline-none focus:shadow-outline-red active:bg-red-600 transition duration-150 ease-in-out">Eliminar</button>
            </form>
        <a href="index" class="inline-block px-4 py-2 font-medium text-white bg-gray-600 rounded-md hover:bg-gray-500 focus:outline-none focus:shadow-outline-red active:bg-gray-600 transition duration-150 ease-in-out">Cancelar</a>
        </div>
    </div>
</body>

</html>
