<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <title>Task List</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://cdn.tailwindcss.com"></script>    </head>
    <body>
        
    <h2 class="flex justify-center items-center mb-4 mt-8 text-3xl font-bold leading-none tracking-tight text-blue-800 md:text-5xl lg:text-6xl dark:text-white">Task Manager</h2>




        
    </body>
</html>